name: "jaffle_shop"
version: "1.0.0"
config-version: 2

# 👇 Update this to point to the name of your Snowflake profile in `profiles.yml`
profile: "snowflake"
# 👆 Either update this or create a profile named `snowflake` within `profiles.yml`

require-dbt-version: ">=1.6.0-b6"

seed-paths: ["jaffle-data"]

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  "dbt_date:time_zone": "America/Los_Angeles"

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
